aapt: /Users/vuminhduc796/Library/Android/sdk/build-tools/30.0.3/aapt

# /home/chunyangchen/Android/Sdk/build-tools/30.0.3/apksigner
# cmd3 = '/Users/han/Library/Android/sdk/build-tools/30.0.3/apksigner sign --ks /Users/han/.android/debug.keystore --ks-pass pass:android --key-pass pass:android ' + apk_path

apk_signer: /Users/vuminhduc796/Library/Android/sdk/build-tools/30.0.3/apksigner sign
  --ks /Users/vuminhduc796/.android/debug.keystore --ks-pass pass:android --key-pass
  pass:android

# false if not m1 chip
arm64: true
auto_login:
  activity: .ui.authentication.mediaauth.AuthActivity
  method: facebook
  packageName: com.Alltrails.alltrails
dark_mode: 'false'
default_facebook:
  password: '1234'
  username: '912345'
emulators:
  alias:
    phone: emulator-5554
    phone-horizontal: emulator-5558
    phone-vertical: emulator-5554
    tablet-horizontal: emulator-5556
    tablet-vertical: emulator-5560
  default:
  - phone-vertical
  - phone-horizontal
  phone-horizontal:
    name: emulator-5558
  phone-vertical:
    name: emulator-5554
  tablet-horizontal:
    name: emulator-5556
  tablet-vertical:
    name: emulator-5560
finished: 'false'
font_size: normal

#  /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/ # For Macbook
#  java_home_path = '/home/dell/tools/jdk1.8.0_45'
#  /home/chunyangchen/android-studio/jre/  # For Ubuntu
#  java_home_path = '/Library/Java/JavaVirtualMachines/openjdk-17.0.1/Contents/Home/' # For Macbook
java_home_path: /Users/vuminhduc796/Library/Java/JavaVirtualMachines/liberica-1.8.0_312/jre

# /home/chunyangchen/Android/Sdk
sdk_platform_path: /Users/vuminhduc796/Library/Android/sdk
updated: ''
zip_align: /Users/vuminhduc796/Library/Android/sdk/build-tools/30.0.3/zipalign
