apk_signer: /Users/leih/Library/Android/sdk/build-tools/29.0.2/apksigner
auto-login:
  default:
    password: '123456'
    username: '123456'
emulators:
  alias:
    phone: emulator-5554
    phone-horizontal: emulator-5558
    phone-vertical: emulator-5554
    tablet-horizontal: emulator-5556
    tablet-vertical: emulator-5560
  default:
  - phone-vertical
  - phone-horizontal
java_home_path: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/
sdk_platform_path: /Users/leih/Library/Android/sdk
